stages:
  - test

test_cypress:
  stage: test
  image: cypress/browsers:latest
  script:
    - npm install
    - npm run cy:run -- --browser chrome --headless
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 week
