name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install cypress@latest # Lub yarn add cypress@latest

      - name: Check Cypress version
        run: npx cypress --version

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless --screenshot-on-error

      - name: Upload Cypress test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
